const otItems = [
// ===== 発達障害 =====
{id:1,name:"自閉スペクトラム症（ASD）",en:"Autism Spectrum Disorder",cat:"発達障害",age:"幼児〜学童",
overview:"社会的コミュニケーションの困難と限定された反復的な行動・興味を主症状とする神経発達症。感覚処理の偏り・不器用さ・こだわり行動を伴うことが多く、OTは感覚統合・ADL・社会参加を包括的に支援する。",
observations:[
{name:"感覚過敏・感覚鈍麻の評価",priority:"high",
why:"ASDの70〜90%に感覚処理の偏りが見られる。触覚・聴覚・視覚・前庭感覚の過敏または鈍麻が、着替え拒否・偏食・パニックの直接原因となることがある。日常困難の根本要因を把握するために必須の評価。",
normal:"感覚プロファイル（SPM等）で特性を把握し、環境調整・感覚ダイエットプログラムを立案する",warn:"感覚刺激による激しい自傷行為・パニック持続→行動支援専門家・医師との連携を検討"},
{name:"ADL（着替え・食事・排泄）の自立度",priority:"high",
why:"感覚過敏・運動協調の困難・手順理解の弱さが複合し、ADL自立が遅れやすい。どのステップが困難かを細分化して評価することで、具体的な支援ポイントが明確になる。",
normal:"タスク分析で各工程を細分化し、視覚的手順表・補助具・環境調整で自立を促進する",warn:"年齢相応から大きく乖離したADL未自立→保護者の負担増大・二次的な自己効力感低下に注意"},
{name:"手先の巧緻性・協調運動",priority:"mid",
why:"ASDの約50%にDCDを合併する。書字・はさみ・箸など微細運動の困難が学校参加を制限することがある。運動評価（MABC-2等）で協調運動のレベルを把握する。",
normal:"段階的な課題設定と成功体験の積み重ね・適切な道具の選定で参加を支援する",warn:""},
{name:"対人関係・遊び場面の観察",priority:"mid",
why:"自由遊び・構造化遊び場面でのアイコンタクト・共同注意・模倣の質を観察する。遊びの形態の発達段階を把握し、段階に応じた関わりを計画する。",
normal:"興味のある活動を媒介として共同注意・順番交代・模倣を促進する",warn:"遊び場面でのみ確認できる感覚探求行動・反復常同行動が激しい→感覚統合の視点でアプローチを検討"},
],
refs:[
"American Psychiatric Association. Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5). 2013.",
"Bodison SC & Parham LD (2018). Specific sensory techniques and sensory environmental modifications for children and youth with sensory integration difficulties. Am J Occup Ther, 72(1).",
"Schaaf RC & Mailloux Z (2015). Clinician's Guide for Implementing Ayres Sensory Integration. AOTA Press.",
"日本作業療法士協会（2020）『自閉スペクトラム症のある子どもへの作業療法支援の手引き』",
"岩崎清隆（編）（2019）『感覚統合療法の理論と実践』協同医書出版社.",
]},
{id:2,name:"感覚過敏（ASD・SPD）",en:"Sensory Hypersensitivity",cat:"発達障害",age:"幼児〜学童",
overview:"触覚・音・光・匂い・衣服等への過敏反応が日常生活を制限する状態。ASD・SPDで多く見られ、OTは感覚統合療法・環境調整・感覚ダイエット（sensory diet）で対応する。",
observations:[
{name:"触覚過敏の程度と部位",priority:"high",
why:"触覚過敏は衣服の素材・タグ・歯磨き・洗髪・散髪の拒否として現れる。軽度の触覚刺激が苦痛として知覚されるため、防御反応として攻撃行動や回避行動が起きやすい。",
normal:"深圧刺激（固有受容覚）の活用・素材選択の工夫・脱感作プログラム（遊びの中でのアプローチ）で過敏を緩和する",warn:"触れるだけでパニック・自傷→医師・心理士との多職種連携、強行しない"},
{name:"音過敏・光過敏の日常への影響",priority:"high",
why:"音過敏は学校での集団生活（チャイム・給食時の食器音・体育館の反響）を困難にする。光過敏は蛍光灯・太陽光への不快感を引き起こし、学習集中に影響する。",
normal:"イヤーマフ・サングラス等補装具の導入・座席配置の工夫・環境音の調整で参加しやすい環境を整える",warn:"感覚刺激で登校困難・給食不参加→学校支援担当と連携し合理的配慮を検討"},
{name:"口腔感覚過敏（偏食）",priority:"mid",
why:"口腔内の触覚・温度・食感への過敏が偏食の主要因になることがある。味よりも食感（ぐにゃっとした・混ざった食感等）への拒否反応が多い。",
normal:"口腔感覚脱感作プログラム・食べられるものから少しずつ食感を広げる段階的アプローチ・栄養士との連携",warn:"著しい偏食で成長障害・栄養不足→医師・栄養士への紹介"},
],
refs:[
"Dunn W (2014). Sensory Profile 2. Pearson.",
"Miller LJ et al. (2007). Concept evolution in sensory integration: A proposed nosology for diagnosis. Am J Occup Ther, 61(2), 135-140.",
"Pfeiffer B et al. (2011). Effectiveness of sensory integration interventions in children with autism spectrum disorders. Am J Occup Ther, 65(1).",
"日本感覚統合学会（監修）（2019）『感覚統合Q&A 改訂第2版』協同医書出版社.",
]},
{id:3,name:"こだわり行動・常同行動",en:"Restricted/Repetitive Behaviors",cat:"発達障害",age:"幼児〜学童",
overview:"特定の手順・順序への固執・反復的な動作（手をひらひらさせる・物を並べる等）がASDに見られる。こだわりが強すぎると活動参加・切り替えを著しく阻害する。OTは感覚統合的視点と環境調整でアプローチする。",
observations:[
{name:"常同行動の機能分析",priority:"high",
why:"常同行動（手をひらひら・回転・揺れ等）は感覚調整のための自己刺激行動であることが多い。行動の頻度・誘発場面・強度を記録し、感覚的ニーズを把握することで代替手段を提案できる。",
normal:"感覚ニーズを満たす代替活動（感覚ツール・スクィーズボール等）を提供し、社会的に受け入れやすい形で表現できるよう支援する",warn:"常同行動が自傷・他害に発展→行動支援専門家・医師との連携が必要"},
{name:"切り替え困難・移行の支援",priority:"high",
why:"活動の切り替えやルーティンの変更が極めて困難なことがある。見通しを持てないことがパニックの主因となる。予告なしの変更に対して激しい情緒的反応が起きやすい。",
normal:"視覚的タイムスケジュール・タイマー（残り時間の可視化）・予告システムの導入で切り替えを支援する",warn:"予測できない変更での強烈なパニック・自傷→構造化の徹底と心理士との連携"},
{name:"こだわりの日常生活・学校生活への影響",priority:"mid",
why:"食事の食べ方の順序・登校ルートの固執・特定の衣服への執着などが日常生活を制限することがある。こだわりの内容と程度・本人と周囲への影響を評価する。",
normal:"こだわりの一部を活用した動機づけ・段階的な柔軟性を育てる活動計画で対応する",warn:""},
],
refs:[
"American Psychiatric Association. DSM-5. 2013.",
"Mesibov GB & Shea V (2010). The TEACCH program in the era of evidence-based practice. J Autism Dev Disord, 40(5), 570-579.",
"Zwaigenbaum L et al. (2015). Early intervention for children with autism spectrum disorder. Pediatrics, 136(Suppl 1).",
"奥田健次（2012）『発達障害の子への応用行動分析（ABA）入門』中央法規出版.",
]},
{id:4,name:"注意欠如多動症（ADHD）",en:"Attention-Deficit/Hyperactivity Disorder",cat:"発達障害",age:"幼児〜学童",
overview:"不注意・多動性・衝動性を主症状とする神経発達症。OTは実行機能・ワーキングメモリ・時間管理・整理整頓などの支援を通じて学校生活・家庭生活への参加を高める。",
observations:[
{name:"着席保持・注意持続の評価",priority:"high",
why:"不注意優勢型では課題への集中持続が困難。多動衝動型では着席維持・順番待ち・衝動的な行動が問題になる。学習場面での注意持続時間・離席頻度・活動参加の質を観察する。",
normal:"環境刺激の最小化・姿勢サポートクッション・タイマー活用・課題の短分割で集中を支援する",warn:"不注意・多動が著しく学習が全く成立しない→医師への紹介（薬物療法の検討）"},
{name:"実行機能（計画・段取り）の評価",priority:"high",
why:"ADHDでは前頭前野機能の弱さにより、物事の計画・優先順位づけ・開始・切り替え・終了が困難。宿題の段取りや持ち物管理の失敗はこの機能の弱さが原因であることが多い。",
normal:"視覚的チェックリスト・ルーティン化・カレンダーシステムなど外部ツールで実行機能を補完する",warn:""},
{name:"整理整頓・持ち物管理",priority:"mid",
why:"ワーキングメモリの弱さと整理整頓スキルの未習得が組み合わさり、忘れ物・失くし物・机の散らかりが慢性化する。物の置き場所の視覚化・ラベリング等の環境調整が有効。",
normal:"定位置を視覚化（写真・ラベル）・カバンの中の仕分けシステム構築・チェックリスト活用で管理を支援する",warn:"忘れ物が多すぎて学校評価・友人関係に深刻な影響→学校との連携・保護者コーチング"},
{name:"衝動性・感情コントロール",priority:"mid",
why:"衝動性により友達とのトラブル・授業中の発言・危険行動が起きやすい。感情の調整困難はADHDで高頻度に見られ、QOLに大きく影響する。",
normal:"感情体温計ツールの活用・感情コントロールのソーシャルスキルトレーニング・セルフモニタリング支援",warn:"衝動的な自傷・激しい感情爆発が繰り返される→医師・心理士との連携"},
],
refs:[
"American Psychiatric Association. DSM-5. 2013.",
"Barkley RA (2015). Attention-Deficit Hyperactivity Disorder: A Handbook for Diagnosis and Treatment, 4th ed. Guilford Press.",
"Pfeiffer B et al. (2014). Sensory processing and sensory integration in ADHD. Phys Occup Ther Pediatr, 35(3).",
"齊藤万比古（編）（2016）『注意欠如・多動症（AD/HD）の診断・治療ガイドライン 第4版』じほう.",
"日本作業療法士協会（2020）『発達障害のある人の作業療法支援』",
]},
{id:5,name:"発達性協調運動症（DCD）",en:"Developmental Coordination Disorder",cat:"発達障害",age:"幼児〜学童",
overview:"運動協調の困難が日常生活・学習・遊びに影響を与える神経発達症。不器用さ・転びやすさ・書字困難・ボール操作困難が代表的。OTは微細・粗大運動の支援と環境調整で参加を促進する。",
observations:[
{name:"協調運動の包括的評価（MABC-2等）",priority:"high",
why:"DCDの診断・支援計画にはMABC-2（Movement ABC-2）等の標準化評価が有用。手先の巧緻性・ボールスキル・静的・動的バランスの各領域を評価し、特に困難な領域を特定する。",
normal:"評価結果に基づき、課題志向アプローチ（COPMとCO-OPアプローチ等）で本人が困っている活動を優先的に支援する",warn:"日常生活のほぼすべての運動課題で困難→医師への報告・多職種連携（PT・ST等）を検討"},
{name:"書字の質・速度・持続性",priority:"high",
why:"書字はDCDで最も多く困難になる活動の一つ。筆圧の調整・文字形成・マス目への収め方・書くスピードに問題が出やすい。疲労により書字持続が困難なケースも多い。",
normal:"鉛筆グリップ・罫線の拡大・姿勢サポート・ICT活用（キーボード・タブレット）の段階的導入で書くことへの参加を維持する",warn:"書字困難で授業についていけず自己肯定感が著しく低下→学校との合理的配慮の検討が急務"},
{name:"自転車・縄跳び等の粗大運動",priority:"mid",
why:"バランス・両側協調・リズムを要する活動（自転車・縄跳び・鉄棒等）が苦手で同年代と比べ習得が遅れる。仲間外れや自己効力感の低下につながることがある。",
normal:"活動を細分化し段階的に練習・補助具の活用・タスク志向アプローチで動機を維持する",warn:""},
{name:"ADLへの影響（ボタン・靴ひも等）",priority:"mid",
why:"ボタン・ファスナー・靴ひも結びなどの手指操作を要するADLが自立しにくい。着替えに時間がかかりすぎることが登校準備・学校生活に支障をきたすことがある。",
normal:"適切な難易度の衣服選択（マジックテープ・ゆとりのある素材）・段階的な練習・成功体験の積み重ね",warn:""},
],
refs:[
"Blank R et al. (2019). European Academy of Childhood Disability (EACD): Recommendations on the definition, diagnosis and intervention of developmental coordination disorder. Dev Med Child Neurol, 61(3).",
"Henderson SE, Sugden DA & Barnett AL (2007). Movement Assessment Battery for Children-2 (MABC-2). Pearson.",
"Polatajko HJ & Mandich A (2004). Enabling Occupation in Children: The Cognitive Orientation to daily Occupational Performance (CO-OP) Approach. CAOT.",
"辻井正次・宮原資英（監修）（2019）『発達性協調運動障害（DCD）』金子書房.",
"Missiuna C et al. (2008). Partnering for change: An innovative school-based occupational therapy service delivery model. Can J Occup Ther, 75(2).",
]},
{id:6,name:"書字障害（発達性ディスレクシア等）",en:"Dysgraphia / Written Language Disorder",cat:"発達障害",age:"学齢期",
overview:"読み書きの習得に著しい困難を示す学習障害。OTは書字に関わる微細運動・視知覚・視覚-運動統合の評価・支援を担い、ICT活用等の合理的配慮の推進も重要な役割となる。",
observations:[
{name:"視覚-運動統合の評価（VMI等）",priority:"high",
why:"書字は視覚情報（文字形）と運動出力（筆記）の統合を要する。VMI（Beery視覚-運動統合検査）等で視知覚・視覚-運動統合・運動協調の各要素を分けて評価し、弱点を特定する。",
normal:"弱い領域に応じた介入（視知覚弱い→視知覚トレーニング、運動弱い→書字練習の工夫）で的確にアプローチする",warn:""},
{name:"書字動作の観察（鉛筆把持・姿勢・筆圧）",priority:"high",
why:"鉛筆の持ち方・筆圧の過不足・姿勢の崩れは書字効率と疲労に直結する。不適切な把持は長時間の筆記での痛み・速度低下の原因となり、学習参加を制限する。",
normal:"適切な鉛筆グリップ・姿勢調整（足台・クッション）・適切な鉛筆の硬さ選択で書字環境を整える",warn:"筆圧が強すぎ鉛筆が頻繁に折れる・痛みを訴える→グリップ・紙への工夫と固有受容覚の感覚統合的アプローチ"},
{name:"ICT活用の評価・導入支援",priority:"mid",
why:"書字困難が著しい場合、キーボード・タブレット・音声入力の活用が学習参加を大きく改善する。本人のICT操作スキルと学校でのICT環境を評価し、段階的に導入する。",
normal:"タイピング練習・タブレットアプリの活用で書くことの代替手段を確立し、学習内容そのものへの集中を可能にする",warn:""},
],
refs:[
"Beery KE & Beery NA (2010). The Beery-Buktenica Developmental Test of Visual-Motor Integration, 6th ed. Pearson.",
"Feder KP & Majnemer A (2007). Handwriting development, competency, and intervention. Dev Med Child Neurol, 49(4), 312-317.",
"Case-Smith J (2002). Effectiveness of school-based occupational therapy intervention on handwriting. Am J Occup Ther, 56(1).",
"奥村智人・若宮英司（編）（2021）『学習に困難のある子どもへの作業療法的アプローチ』三輪書店.",
"文部科学省（2021）『障害のある子供の教育支援の手引』",
]},
{id:7,name:"知的発達症（知的障害）",en:"Intellectual Developmental Disorder",cat:"発達障害",age:"幼児〜学童",
overview:"知的機能と適応行動の両方に有意な制約がある状態。OTは認知特性に合わせたADL・余暇・社会参加支援を行い、できることを最大限に活かした自立生活を支援する。",
observations:[
{name:"適応行動の評価（VABS等）",priority:"high",
why:"知的発達症の支援計画には知的機能だけでなく、実際の生活における適応行動（コミュニケーション・日常生活・社会的スキル・運動スキル）の評価が必須。VinelandII等で現状を把握する。",
normal:"強みの活用・視覚支援・反復練習・スモールステップで各生活スキルの習得を促進する",warn:""},
{name:"ADL自立度と介助量の評価",priority:"high",
why:"食事・着替え・排泄・整容の各ADLでどの程度自立しているか・どこで詰まっているかを細分化して評価する。介助量の最小化と自立の促進はQOL向上と介護者負担軽減に直結する。",
normal:"タスク分析・視覚的手順書・一貫した教え方（プロンプト法の段階的フェーディング）でADL自立を促進する",warn:"ADLが全介助で退行傾向→健康状態の変化（感染症・精神疾患等）の可能性を医師に報告"},
{name:"認知特性（視覚優位か言語優位か）の把握",priority:"mid",
why:"視覚的情報処理が強い場合、写真・絵カード・動画による指導が言語説明より効果的。認知特性に合わせた指導法の選択が学習効率を大きく左右する。",
normal:"本人の認知特性（視覚・言語・動作）に合わせた指導媒体を選択し、理解しやすい形で教える",warn:""},
],
refs:[
"Sparrow SS, Cicchetti DV & Saulnier CA (2016). Vineland Adaptive Behavior Scales, Third Edition (VABS-3). Pearson.",
"American Association on Intellectual and Developmental Disabilities (AAIDD). Intellectual Disability: Definition, Classification, and Systems of Supports, 12th ed. 2021.",
"Snell ME & Brown F (2011). Instruction of Students with Severe Disabilities, 7th ed. Pearson.",
"日本知的障害者福祉協会（2019）『知的障害のある人の支援ガイドライン』",
"厚生労働省（2017）『障害者の日常生活及び社会生活を総合的に支援するための法律（障害者総合支援法）』",
]},

// ===== 神経・先天性疾患 =====
{id:8,name:"脳性麻痺（痙直型）",en:"Spastic Cerebral Palsy",cat:"神経・先天性疾患",age:"乳幼児〜学童",
overview:"痙縮による運動制限・姿勢異常が主症状。上肢機能障害・姿勢保持困難・ADL制限が多くみられる。OTは上肢機能の最大化・ADL自立支援・補装具・環境調整を担う。",
observations:[
{name:"上肢機能（筋緊張・関節可動域・随意性）の評価",priority:"high",
why:"痙縮による関節可動域制限・協調運動の困難が上肢ADLを制限する。MACS（手指分類システム）等で機能レベルを把握し、現実的な目標設定の根拠とする。",
normal:"ポジショニング・関節可動域訓練・機能的な作業活動・CI療法（適応がある場合）で上肢機能を最大化する",warn:"急速な筋緊張増大・新たな拘縮形成→医師への報告（ボツリヌス毒素注射等の検討）"},
{name:"姿勢保持・シーティング評価",priority:"high",
why:"座位での姿勢保持が不安定だと、上肢操作・食事・学習・コミュニケーション全般に影響する。体幹の安定性が手の機能を最大限発揮するための基盤となる。",
normal:"適切な車椅子・椅子のフィッティング・姿勢補助具（クッション・サポート）の選定・定期的な再評価",warn:"座位保持困難で体幹前傾・側弯進行→PTとの連携・医師への報告（側弯対策の検討）"},
{name:"食事動作（摂食機能）の評価",priority:"high",
why:"上肢機能・口腔機能・姿勢が食事動作に複合的に影響する。自助具（スプーン・皿のふち等）の選定と適切なポジショニングで自力摂取を最大化する。",
normal:"自助具の導入・適切な姿勢設定・食器の工夫（滑り止めマット・ユニバーサルデザイン食器）で自力摂取を支援する",warn:"誤嚥・むせが著しい→STへの紹介・医師への報告（嚥下評価の実施）"},
{name:"ADL・補装具・環境調整",priority:"mid",
why:"更衣・排泄・入浴等のADLは機能レベルに応じた目標設定と補装具・環境調整の組み合わせが重要。できることとできないことを正確に評価し、自立と安全を両立させる。",
normal:"セルフケア補装具（着替えの工夫・手すり等）の選定・バリアフリー環境の提案で安全なADL遂行を支援する",warn:""},
],
refs:[
"Eliasson AC et al. (2006). The Manual Ability Classification System (MACS) for children with cerebral palsy. Dev Med Child Neurol, 48(7), 549-554.",
"Palisano R et al. (1997). Development and reliability of a system to classify gross motor function in children with cerebral palsy. Dev Med Child Neurol, 39(4), 214-223.",
"Sakzewski L et al. (2014). Efficacy of upper limb therapies for unilateral cerebral palsy. Pediatrics, 133(1).",
"才藤栄一・植松光俊（編）（2020）『脳性麻痺リハビリテーションガイドライン 第2版』医歯薬出版.",
"日本作業療法士協会（2018）『脳性麻痺に対する作業療法支援の手引き』",
]},
{id:9,name:"二分脊椎",en:"Spina Bifida",cat:"神経・先天性疾患",age:"乳幼児〜学童",
overview:"脊髄の先天性奇形による下肢麻痺・排泄障害が主症状。上肢機能は比較的保たれることが多い。OTはADL自立・排泄管理・学校生活・自己管理スキルの獲得を支援する。",
observations:[
{name:"ADL自立度（上半身・移動）の評価",priority:"high",
why:"下肢麻痺のレベルに応じてADLの制限が異なる。更衣（特に下衣・靴下）・床からの立ち上がり・車椅子移乗等の評価と、自立促進のための工夫を検討する。",
normal:"下衣着脱補助具・適切なポジショニング・段階的な自立練習で更衣・移乗の自立度を高める",warn:""},
{name:"排泄管理（導尿・排便管理）の自己管理",priority:"high",
why:"間欠導尿・排便管理の自己管理スキルは年齢とともに本人が担う必要がある。手指巧緻性・体幹機能・認知機能が自己導尿の自立に直結する。学齢期を見据えた練習計画が重要。",
normal:"手指巧緻性訓練・適切な姿勢設定・スモールステップでの導尿手技練習・プライバシー管理の自立支援",warn:"手指機能の制限が強く自己導尿困難→医師・看護師・泌尿器科との連携"},
{name:"感覚障害部位のスキンケア自己管理",priority:"mid",
why:"感覚麻痺がある部位では褥瘡・外傷に気づきにくい。自己スキンケアと体位変換の習慣化が二次的合併症の予防に不可欠。自己管理スキルは年齢とともに段階的に教える。",
normal:"皮膚の自己チェック習慣・体圧分散クッション・除圧動作の学習で皮膚トラブルを予防する",warn:"感覚麻痺部位の皮膚トラブル発見遅れ→医師・看護師への報告"},
],
refs:[
"Liptak GS & Dosa NP (2010). Myelomeningocele. Pediatr Rev, 31(11), 443-450.",
"Law M et al. (1998). Canadian Occupational Performance Measure (COPM), 3rd ed. CAOT Publications.",
"Barf HA et al. (2003). Concerns of parents with spina bifida. Dev Med Child Neurol, 45(3), 183-186.",
"日本二分脊椎症協会（編）（2018）『二分脊椎医療ガイドライン』金原出版.",
]},
{id:10,name:"てんかん（発達への影響）",en:"Epilepsy (Developmental Impact)",cat:"神経・先天性疾患",age:"乳幼児〜学童",
overview:"てんかん発作自体より、頻回発作・抗てんかん薬の影響・高次脳機能障害の合併が発達・学習・日常生活に影響することがある。OTは発作後の状態評価と日常生活・学校参加の支援を担う。",
observations:[
{name:"発作後（ポスタル期）の状態評価",priority:"high",
why:"全般発作後は疲労・混乱・眠気（Todd麻痺含む）が続く。発作後の状態が日常生活・学習に与える影響を把握し、回復時間を考慮したスケジュール調整が必要。",
normal:"発作後の安全確保・休息時間の確保・活動再開のタイミングを本人・保護者・学校と共有する",warn:"発作後のTodd麻痺が長引く・意識回復が遅い→医師への報告"},
{name:"注意・記憶・学習への影響",priority:"high",
why:"てんかんに合併する高次脳機能障害（注意障害・記憶障害・処理速度の低下）が学習困難の原因となることがある。薬物療法の変更後に認知機能が変化することも多い。",
normal:"認知機能の定期的な評価・補完戦略（メモ・チェックリスト・視覚化）の導入・学校への合理的配慮の提案",warn:"認知機能の急激な低下→医師への報告（発作増悪・薬剤変更の検討）"},
{name:"安全管理と活動参加のバランス",priority:"mid",
why:"発作への不安から活動制限が過剰になり社会参加・自立が制限されることがある。リスク評価に基づき、安全を確保しつつ最大限の活動参加を支援することがOTの重要な役割。",
normal:"発作の型・頻度・誘発因子を把握し、制限すべき活動と参加可能な活動を医師・保護者・学校と整理する",warn:""},
],
refs:[
"日本てんかん学会診療ガイドライン委員会（2018）『てんかん診療ガイドライン2018』医学書院.",
"Hamiwka LD & Wirrell EC (2009). Comorbidities in pediatric epilepsy. Pediatr Neurol, 40(2), 95-99.",
"Berg AT et al. (2010). Revised terminology and concepts for organization of seizures and epilepsies. Epilepsia, 51(4), 676-685.",
"大田原俊輔（監修）（2020）『小児のてんかん診療ガイド』診断と治療社.",
]},
{id:11,name:"ダウン症候群",en:"Down Syndrome (Trisomy 21)",cat:"神経・先天性疾患",age:"乳幼児〜学童",
overview:"21トリソミーによる染色体疾患。筋緊張低下・発達遅滞・特徴的な顔貌が主症状。OTは筋緊張低下を考慮した姿勢保持・ADL・手指巧緻性・社会参加の支援を行う。",
observations:[
{name:"筋緊張低下と姿勢保持の評価",priority:"high",
why:"低緊張は姿勢保持・バランス・運動発達全般に影響する。腹臥位・座位・立位での姿勢保持の質と代償パターンを評価し、PTと連携して適切な発達支援を行う。",
normal:"発達段階に応じた姿勢支援・固有受容覚・前庭感覚を活性化する遊び活動でトーンアップを促す",warn:"著しい低緊張で座位保持困難→PT・医師との連携・補助具の導入"},
{name:"手指巧緻性・ADLスキルの評価",priority:"high",
why:"低緊張と関節の過可動性により、ピンチ力・握力の弱さ・手指操作の不器用さが見られやすい。食事・着替え・文字を書くなどのADLへの影響を評価する。",
normal:"機能的な遊び活動（粘土・ビーズ・パズル等）で手指機能を高め、ADLのスモールステップ練習と組み合わせる",warn:""},
{name:"コミュニケーション・社会参加の支援",priority:"mid",
why:"言語発達の遅れがあることが多い。AAC（補助代替コミュニケーション）の活用や、絵カード・写真等の視覚支援で表現・理解を補完する。STとの連携が重要。",
normal:"視覚支援ツール・シンボルコミュニケーション・サインの活用でコミュニケーションを補完し社会参加を促進する",warn:""},
],
refs:[
"Bull MJ & the Committee on Genetics (2011). Health supervision for children with Down syndrome. Pediatrics, 128(2), 393-406.",
"Lott IT & Dierssen M (2010). Cognitive deficits and associated neurological complications in individuals with Down syndrome. Lancet Neurol, 9(6), 623-633.",
"日本ダウン症協会（2020）『ダウン症のある子どもたちの発達支援ガイドブック』",
"七木田敦（編）（2017）『ダウン症候群の作業療法』三輪書店.",
]},
{id:12,name:"22q11.2欠失症候群",en:"22q11.2 Deletion Syndrome",cat:"神経・先天性疾患",age:"幼児〜学童",
overview:"22番染色体の微細欠失による多彩な症状（心奇形・口蓋裂・免疫不全・発達遅滞等）を呈する症候群。OTは発達支援・ADL・学習支援・ソーシャルスキルを中心に支援する。",
observations:[
{name:"発達評価（認知・運動・ADL）",priority:"high",
why:"軽度〜中等度の知的発達症・処理速度の低下・視空間認知の困難が学習に影響することが多い。強みと弱みのプロフィールを把握し、支援計画に活かす。",
normal:"視覚支援・処理速度の遅さに配慮した課題設定・段階的なADL支援で参加を促進する",warn:""},
{name:"学校生活・学習支援のニーズ評価",priority:"mid",
why:"算数・書字・注意機能の困難が多く、学校場面で支援が必要なことが多い。学習支援員・合理的配慮の活用を検討し、学校と連携して支援体制を整える。",
normal:"強みを活かした学習支援・視覚的提示・反復練習・ICT活用で学習参加を支援する",warn:""},
],
refs:[
"Swillen A & McDonald-McGinn D (2015). Developmental trajectories in 22q11.2 deletion syndrome. Am J Med Genet C Semin Med Genet, 169(2), 172-181.",
"Bearden CE et al. (2001). The neurocognitive phenotype of the 22q11.2 deletion syndrome. Mol Psychiatry, 6(2), 129-140.",
"日本22q11.2欠失症候群家族会（2019）『22q11.2欠失症候群ガイドブック』",
]},

// ===== 感覚統合 =====
{id:13,name:"感覚統合障害（SPD）",en:"Sensory Processing Disorder",cat:"感覚統合",age:"幼児〜学童",
overview:"感覚入力の登録・調整・統合に困難を持つ状態。OTは感覚統合理論（Ayres）に基づいた評価（SIPT等）と介入で、神経系の感覚処理能力の向上を目指す。",
observations:[
{name:"感覚処理パターンの評価（SPM・感覚プロファイル等）",priority:"high",
why:"視覚・聴覚・触覚・前庭感覚・固有受容覚・嗅覚・味覚の各感覚チャンネルの過敏・低登録・感覚探求・感覚回避のパターンを評価する。日常生活の困難の感覚的原因を特定する。",
normal:"感覚プロファイルに基づき感覚ダイエット（sensory diet）を立案し、日常生活での感覚調整を支援する",warn:"感覚刺激で頻繁なパニック・自傷→医師・心理士との連携・安全の確保"},
{name:"前庭感覚（バランス・回転刺激）の評価",priority:"high",
why:"前庭感覚の過敏は乗り物酔い・頭を動かす活動への強い抵抗として現れる。鈍麻では過度な回転・揺れ探求行動が見られる。ADLではバランス動作・着替え時の姿勢に影響する。",
normal:"段階的な前庭感覚入力（揺れ・回転の量と質を調整）・感覚統合療法アプローチで神経系の統合を促進する",warn:""},
{name:"固有受容覚の問題（力加減・姿勢保持）",priority:"high",
why:"固有受容覚の問題は鉛筆を折る・人を強くたたく・姿勢が崩れやすい・疲れやすいなどとして現れる。関節・筋肉からのフィードバックが適切に処理されないため力加減の調整が難しい。",
normal:"深圧刺激・重い物を運ぶ活動・抵抗のある運動で固有受容覚入力を増やし力加減と姿勢保持を改善する",warn:""},
],
refs:[
"Ayres AJ (1972). Sensory Integration and Learning Disorders. Western Psychological Services.",
"Ayres AJ (2005). Sensory Integration and the Child: Understanding Hidden Sensory Challenges, 25th anniversary ed. Western Psychological Services.",
"Parham LD & Mailloux Z (2010). Sensory integration. In: Case-Smith J (ed), Occupational Therapy for Children, 6th ed. Mosby Elsevier.",
"Miller LJ et al. (2007). Concept evolution in sensory integration. Am J Occup Ther, 61(2), 135-140.",
"日本感覚統合学会（監修）（2019）『感覚統合Q&A 改訂第2版』協同医書出版社.",
]},
{id:14,name:"前庭感覚障害（バランス不良）",en:"Vestibular Processing Disorder",cat:"感覚統合",age:"幼児〜学童",
overview:"前庭感覚の処理困難によりバランス・空間認識・目の動き（眼球運動）に影響が出る状態。片足立ち・平均台・自転車などに困難を示す。",
observations:[
{name:"静的・動的バランスの評価",priority:"high",
why:"片足立ち・つぎ足歩行・不安定面でのバランスを評価し、前庭感覚処理の状態を把握する。学校の体育活動・日常の階段昇降・着替え時の転倒リスクを評価する。",
normal:"感覚統合的アプローチ（揺れ・回転・バランス活動）・固有受容覚強化でバランス機能を向上させる",warn:"頻繁な転倒・骨折リスク→安全な環境整備・PTへの紹介"},
{name:"乗り物酔い・高所への不安",priority:"mid",
why:"前庭過敏では乗り物酔いが著しく・高所恐怖・エレベーター・階段への強い不安が見られることがある。これらが外出や学校行事への参加を制限することがある。",
normal:"段階的な脱感作・緩やかな前庭刺激の提供・環境調整（視覚的固定点の活用等）で過敏を軽減する",warn:""},
],
refs:[
"Ayres AJ (1972). Sensory Integration and Learning Disorders. Western Psychological Services.",
"Rine RM & Wiener-Vacher S (2013). Evaluation and treatment of vestibular dysfunction in children. NeuroRehabilitation, 32(3), 507-518.",
"日本感覚統合学会（監修）（2019）『感覚統合Q&A 改訂第2版』協同医書出版社.",
]},

// ===== 運動・協調 =====
{id:15,name:"書字困難（筆圧・文字形成）",en:"Handwriting Difficulties",cat:"運動・協調",age:"学齢期",
overview:"筆圧の調整困難・文字形成の不正確さ・マス目内に文字が収まらないなどの書字困難。視知覚・視覚-運動統合・固有受容覚・微細運動の複合的な問題として現れることが多い。",
observations:[
{name:"書字産物（サンプル）の分析",priority:"high",
why:"実際の書字サンプルを収集し、文字形成・サイズの一貫性・行間・スペーシング・全体的な読みやすさを評価する。どの側面に問題があるかで介入の方向性が変わる。",
normal:"書字の評価（WRAVMA等）と書字サンプル分析を組み合わせ、具体的な問題領域を特定して介入する",warn:"書字が全く判読不能・速度が極端に遅い→ICT代替の検討・合理的配慮の申請"},
{name:"鉛筆把持・筆圧の観察",priority:"high",
why:"不適切な三指つまみ（グリップ）は長時間の書字で疲労・痛みを引き起こし、書字拒否につながる。過剰筆圧は紙を破く・鉛筆芯が折れる・消しゴムで紙が破れる原因になる。",
normal:"鉛筆グリップ補助具・適切な硬さの鉛筆選択・固有受容覚活動（重い物を押す・引くなど）で筆圧を正常化する",warn:""},
{name:"視知覚・空間認知の評価（TVPS等）",priority:"mid",
why:"文字の形の認識・マス目の理解・文字と文字のスペーシングには視知覚と空間認知が関与する。視知覚の弱さが書字困難の原因となっている場合、運動練習だけでは改善しない。",
normal:"視知覚課題（パズル・迷路・点つなぎ等）と書字練習を組み合わせ、視知覚-運動統合を段階的に高める",warn:""},
],
refs:[
"Beery KE & Beery NA (2010). Beery-Buktenica VMI, 6th ed. Pearson.",
"Feder KP & Majnemer A (2007). Handwriting development, competency, and intervention. Dev Med Child Neurol, 49(4), 312-317.",
"Denton PL et al. (2006). Handwriting program for third-grade students. Am J Occup Ther, 60(6).",
"奥村智人・若宮英司（編）（2021）『学習に困難のある子どもへの作業療法的アプローチ』三輪書店.",
]},
{id:16,name:"はさみ操作困難",en:"Scissor Skill Difficulties",cat:"運動・協調",age:"幼児〜学齢期",
overview:"はさみの開閉・両手の協調・目と手の協調に困難を示す状態。幼稚園・保育園・小学校での工作・図工活動への参加を制限する。",
observations:[
{name:"はさみ動作の段階的評価",priority:"high",
why:"はさみ操作は①開閉②直線切り③曲線切り④形の切り抜きと段階があり、どの段階で困難かを特定する。現在のレベルから始め、次の段階へ段階的に進める。",
normal:"適切な難易度の課題設定・ループはさみ等補助具の活用・動作の分解練習で段階的にスキルアップする",warn:""},
{name:"両手協調の評価",priority:"high",
why:"はさみ操作は利き手でのはさみ操作と非利き手での紙回転の両手協調を要する。片方の手が上手く動かせない場合、一方の動作に集中して練習する。",
normal:"両手協調を高める段階的活動（クランプ・洗濯バサミ→はさみへの移行）と非利き手の紙保持練習を組み合わせる",warn:""},
],
refs:[
"Schneck CM & Battaglia C (1992). Linking sensory processing deficits to functional deficits. Am J Occup Ther, 46(5).",
"Case-Smith J (1995). The relationships among sensorimotor components, fine motor skill, and functional performance in preschool children. Am J Occup Ther, 49(7).",
"日本作業療法士協会（2020）『子どもの作業療法 微細運動支援マニュアル』",
]},
{id:17,name:"箸操作困難",en:"Chopstick Use Difficulties",cat:"運動・協調",age:"幼児〜学齢期",
overview:"箸操作は手指の分離動作・協調・固有受容覚の高度な統合を要する。スプーン→フォーク→箸の段階的習得が基本。学校給食での参加に影響することがある。",
observations:[
{name:"スプーン・フォーク使用の評価（前段階）",priority:"high",
why:"箸操作が困難な場合、スプーン・フォーク操作が十分確立されているかを確認する。スプーン操作（すくう・こぼさず口へ運ぶ）が不安定な場合、箸練習より前段階のスキル向上を優先する。",
normal:"スプーン→フォーク→トレーニング箸→通常箸の段階的な移行計画を立て、成功体験を積み重ねる",warn:""},
{name:"手指の分離動作・三指つまみの質",priority:"high",
why:"箸操作には中指・薬指・小指を曲げたまま人差し指・中指・親指だけを独立させる手指の分離動作が必要。この動作が未成熟な場合、箸練習前に手指分離の基礎練習を行う。",
normal:"ピンセット・洗濯バサミ・トレーニング箸等の段階的ツールで手指分離動作を練習する",warn:""},
],
refs:[
"Pehoski C (1995). Object manipulation in infants and children. In: Henderson A & Pehoski C (eds), Hand Function in the Child. Mosby.",
"Case-Smith J & Bigsby R (2000). Posture and fine motor assessment of infants. Am J Occup Ther.",
"日本作業療法士協会（2020）『子どもの作業療法 微細運動支援マニュアル』",
]},
{id:18,name:"ボタン・ファスナー困難",en:"Dressing Fastener Difficulties",cat:"運動・協調",age:"幼児〜学齢期",
overview:"ボタン・ファスナー・スナップ等の衣服の締め具操作が困難な状態。手指巧緻性・協調・視覚-運動統合が関与する。更衣の自立を阻む要因として頻繁に相談される。",
observations:[
{name:"各種ファスナー操作の評価",priority:"high",
why:"ボタン（大→小）・ファスナー（引き手の大きさ）・スナップ・マジックテープと難易度が異なる。どの操作が困難かを特定し、現在のレベルから始める段階的練習を計画する。",
normal:"大きなボタン→小さなボタンの段階・ドレッシングボードでの練習→実際の衣服での練習という段階的アプローチ",warn:""},
{name:"視覚-運動統合・手の協調の評価",priority:"mid",
why:"ボタン操作は小さな対象を視覚でとらえながら両手で操作する高度な視覚-運動統合を要する。視知覚や両手協調の問題が根底にある場合は、その問題にもアプローチする。",
normal:"衣服の操作練習と並行して視知覚・両手協調の基礎活動（ビーズ・粘土・積み木等）を取り入れる",warn:""},
],
refs:[
"Exner CE (2010). Development of hand skills. In: Case-Smith J (ed), Occupational Therapy for Children, 6th ed. Mosby Elsevier.",
"Shepherd J (2010). Activities of daily living and adaptations for independent living. In: Case-Smith J (ed), Occupational Therapy for Children.",
"日本作業療法士協会（2018）『ADL支援の手引き―小児編』",
]},
{id:19,name:"姿勢保持困難（座位・立位）",en:"Postural Control Difficulties",cat:"運動・協調",age:"幼児〜学童",
overview:"重力に抗して姿勢を保つ能力の低下。「姿勢が悪い」「すぐに机に寄りかかる」「床にべたっと座る」などとして観察される。体幹筋力・固有受容覚・前庭感覚の統合が関与する。",
observations:[
{name:"座位保持の質・持続時間の評価",priority:"high",
why:"学習場面での着席姿勢は集中・書字・視覚的注意に直接影響する。体幹の安定性不足が学習困難・疲れやすさの原因になることがある。",
normal:"体幹安定化活動（トランポリン・バランスボール等）・適切な椅子と足台の設定・授業中の姿勢休憩で座位保持を支援する",warn:""},
{name:"体幹筋力・固有受容覚の評価",priority:"high",
why:"低緊張・固有受容覚処理の弱さが姿勢保持困難の主因になることが多い。感覚統合的アプローチと体幹強化活動を組み合わせてアプローチする。",
normal:"重力に抗した活動（腹臥位遊び・腹筋・背筋を使う遊び）・固有受容覚入力を多く含む活動で体幹機能を高める",warn:"姿勢保持が著しく困難で側弯疑い→医師・PTへの報告・精査"},
],
refs:[
"Rosenblum S & Josman N (2003). The relationship between postural control and fine manual dexterity. Phys Occup Ther Pediatr, 23(4), 47-60.",
"Ayres AJ (1972). Sensory Integration and Learning Disorders. Western Psychological Services.",
"日本作業療法士協会（2020）『姿勢とシーティングの作業療法的アプローチ』",
]},
{id:20,name:"協調運動困難（縄跳び・ボール運動）",en:"Motor Coordination Difficulties",cat:"運動・協調",age:"幼児〜学童",
overview:"リズムに合わせた運動・両側協調・目と手の協調を要する活動（縄跳び・ボール操作・鉄棒等）が著しく困難な状態。体育参加・休み時間の遊びに影響し、仲間外れのリスクもある。",
observations:[
{name:"両側協調運動の評価",priority:"high",
why:"縄跳び・太鼓たたき・なわとびは両手足の協調を要する。両側協調の評価（連続まねっこ動作・拍手模倣等）で困難な側面を特定し、段階的なアプローチを計画する。",
normal:"両側協調の段階的練習（左右対称→交互動作→ランダム）・リズム感を育てる音楽的活動を組み合わせる",warn:""},
{name:"目と手の協調（ボール操作）の評価",priority:"mid",
why:"ボールをキャッチする・転がす・蹴るなどの活動は視覚で軌跡を予測しながら身体を動かす目と手の協調を要する。サイズ・速度を調整した段階的練習が有効。",
normal:"大きくゆっくりのボールから始め・距離・速度・サイズを段階的に調整して目と手の協調を練習する",warn:""},
],
refs:[
"Blank R et al. (2019). European Academy of Childhood Disability guidelines for DCD. Dev Med Child Neurol, 61(3).",
"Missiuna C et al. (2006). Described as a 'clumsy child': A qualitative study of parents' experiences. Can J Occup Ther, 73(2).",
"辻井正次・宮原資英（監修）（2019）『発達性協調運動障害（DCD）』金子書房.",
]},

// ===== 日常生活（ADL） =====
{id:21,name:"食事動作困難（スプーン・コップ・咀嚼）",en:"Self-Feeding Difficulties",cat:"日常生活（ADL）",age:"乳幼児〜学童",
overview:"スプーン・フォーク・コップ操作や咀嚼・飲み込みの困難。運動発達の遅れ・口腔感覚の問題・座位保持困難など複数の要因が関与する。OTは自助具選定・姿勢設定・段階的練習で自力摂取を支援する。",
observations:[
{name:"食事動作の観察（姿勢・道具操作・こぼし）",priority:"high",
why:"食事場面の直接観察で、こぼし量・スプーンの持ち方・すくい方・口まで運ぶ動作・コップ操作の質を評価する。どのステップが困難かを特定し、具体的な支援策を立案する。",
normal:"姿勢設定（足底接地・座面高さ調整）・自助具（グリップ付きスプーン・ふちの高い皿・コップホルダー等）の選定で自力摂取を支援する",warn:"むせ・誤嚥が頻繁→STへの紹介・医師への報告（嚥下評価の実施）"},
{name:"口腔機能（咀嚼・食感への反応）の評価",priority:"high",
why:"口腔感覚過敏・咀嚼力の低下・口の開閉協調の問題が偏食・食事拒否に関与することがある。食べられる食形態と拒否の多い食形態を把握し、STと連携して対応する。",
normal:"口腔感覚の脱感作アプローチ・食形態の段階的調整・食べられる食材の分析と拡大計画でアプローチする",warn:"体重増加不良・著しい偏食で栄養不足→STへの紹介・医師・栄養士との連携"},
],
refs:[
"Shepherd J (2010). Activities of daily living and adaptations for independent living. In: Case-Smith J (ed), Occupational Therapy for Children.",
"Morris SE & Klein MD (2000). Pre-Feeding Skills, 2nd ed. Therapy Skill Builders.",
"日本摂食嚥下リハビリテーション学会（2018）『嚥下障害のある子どもへの支援ガイドライン』",
"日本作業療法士協会（2020）『食事動作支援の手引き―小児編』",
]},
{id:22,name:"更衣困難",en:"Dressing Difficulties",cat:"日常生活（ADL）",age:"幼児〜学童",
overview:"着脱の順序理解・空間認知・微細運動・感覚の複合的な問題として更衣困難が現れる。朝の準備に時間がかかりすぎることが親子関係のストレスになることもある。",
observations:[
{name:"更衣動作の段階的評価（タスク分析）",priority:"high",
why:"更衣を「上衣脱ぎ→上衣着用→下衣脱ぎ→下衣着用→靴下→靴」と細分化し、どのステップが困難かを特定する。視覚運動統合・空間認知・感覚の問題をそれぞれ評価する。",
normal:"タスク分析に基づいた段階的練習・視覚的手順表（写真付き）・スモールステップで更衣の自立を促進する",warn:""},
{name:"衣服への感覚過敏の評価",priority:"mid",
why:"素材・タグ・縫い目・きつさへの感覚過敏が更衣拒否の原因になることがある。どの素材・どの感触を嫌がるかを特定し、許容できる衣服から練習する。",
normal:"柔らかい素材・タグなし衣服・ゆとりのあるサイズを選択し、感覚過敏に配慮した衣服選びを保護者に提案する",warn:""},
],
refs:[
"Shepherd J (2010). Activities of daily living. In: Case-Smith J (ed), Occupational Therapy for Children.",
"Dunn W (2014). Sensory Profile 2. Pearson.",
"日本作業療法士協会（2018）『ADL支援の手引き―小児編』",
]},
{id:23,name:"排泄自立困難",en:"Toileting Difficulties",cat:"日常生活（ADL）",age:"幼児〜学童",
overview:"おむつからトイレへの移行・手順理解・衣服の着脱・後始末の自立が遅れる状態。感覚の問題・認知的理解の遅れ・運動機能の困難が複合することがある。",
observations:[
{name:"排泄自立の段階評価",priority:"high",
why:"排泄自立には①便意・尿意の認識②タイミングでのトイレ移動③衣服の着脱④用を足す⑤後始末と多くのステップがある。現在どのステップまで自立しているかを特定する。",
normal:"現在のレベルから次のステップへのスモールステップ・視覚的手順書・定時誘導から始める段階的アプローチ",warn:"便意・尿意の認識が全くない→医師への報告（感覚統合・神経学的評価の検討）"},
{name:"衣服の着脱（トイレ場面での）の評価",priority:"mid",
why:"急いでいる場面での衣服の着脱が困難で間に合わないことが多い。ボタン・ベルト・ファスナーを素早く外す練習と、簡単に着脱できる衣服への変更を検討する。",
normal:"マジックテープ・ゴム式パンツなど着脱しやすい衣服の選択・着脱練習で間に合う確率を高める",warn:""},
],
refs:[
"Shepherd J (2010). Activities of daily living. In: Case-Smith J (ed), Occupational Therapy for Children.",
"Gray M et al. (2011). Toilet training children with disabilities. In: Case-Smith J & O'Brien JC (eds), Occupational Therapy for Children.",
"厚生労働省（2018）『障害のある子どもの日常生活自立支援プログラム』",
]},

// ===== 学校・社会参加 =====
{id:24,name:"着席保持・集中困難（学習場面）",en:"In-seat Behavior & Attention Difficulties",cat:"学校・社会参加",age:"幼児〜学童",
overview:"授業中に座っていられない・集中が続かない・離席が多いなどの困難。ADHDやSPD・姿勢保持困難が背景にあることが多い。OTは感覚・姿勢・環境の視点からアプローチする。",
observations:[
{name:"着席困難の要因分析（感覚vs姿勢vs注意）",priority:"high",
why:"離席・体動の多さは感覚探求（動きたい）・姿勢保持困難（座れない）・注意持続困難（集中できない）の3つが原因として考えられ、それぞれアプローチが異なる。観察・評価で主要因を特定する。",
normal:"感覚ダイエット（授業前の感覚入力）・動的シーティング（バランスクッション）・課題の短分割で着席維持を支援する",warn:""},
{name:"授業前の感覚調整（センサリーダイエット）",priority:"high",
why:"授業前に固有受容覚・前庭感覚を適度に満たすことで、授業中の覚醒レベルを最適化できることがある。学校での実施可能な感覚活動を提案する。",
normal:"廊下での荷物運搬・壁プッシュ・お手玉・スクィーズボールなど授業中に使える感覚ツールを学校と検討する",warn:""},
{name:"板書・ノート作成への支援",priority:"mid",
why:"黒板の文字を見てノートに書き写すには視覚記憶・視知覚・書字スキルが複合的に必要。どのプロセスが困難かを特定し、それぞれに対応する。",
normal:"拡大写真・記入フォーム・ICT活用（タブレット撮影等）・補助線ノートなど合理的配慮を学校と連携して整備する",warn:"板書が全くできず授業についていけない→合理的配慮の申請・担任との緊急連携"},
],
refs:[
"Pfeiffer B et al. (2008). Effectiveness of sensory integration interventions in children with ADHD. Am J Occup Ther, 62(3).",
"Gioia GA et al. (2000). BRIEF: Behavior Rating Inventory of Executive Function. Psychological Assessment Resources.",
"文部科学省（2021）『障害のある子供の教育支援の手引』",
"日本作業療法士協会（2020）『学校作業療法実践ガイド』",
]},
{id:25,name:"体育活動困難（縄跳び・鉄棒・マット）",en:"Physical Education Participation Difficulties",cat:"学校・社会参加",age:"学童",
overview:"体育の授業における縄跳び・鉄棒・マット運動・ボール運動等への参加困難。運動の失敗経験が「体育嫌い」「運動嫌い」につながり、長期的な活動参加の低下を招くことがある。",
observations:[
{name:"体育授業での参加状況の把握",priority:"high",
why:"どの種目で困難があるか・どの程度参加できているか・心理的な影響（参加拒否・泣く・恥ずかしがる等）を把握する。教師への聴取と可能なら参与観察で実態を把握する。",
normal:"困難な種目の段階的な目標設定・本人が「できた」を感じられる目標設定・教師との連携で体育参加を支援する",warn:"体育が原因で不登校・学校不安→担任・養護教諭との連携・心理士への紹介"},
{name:"失敗体験の影響（自己効力感）の評価",priority:"mid",
why:"DCDの子どもは運動の失敗体験が積み重なり自己効力感・自尊心が低下しやすい。「どうせできない」という諦めが練習意欲を失わせる。成功体験を積ませることがOT介入の重要な要素。",
normal:"必ず成功できる難易度設定・できたことの言語化・得意な活動での達成感を積み重ねて自己効力感を回復する",warn:""},
],
refs:[
"Missiuna C et al. (2006). A 'clumsy child': A qualitative study of parents' experiences. Can J Occup Ther, 73(2).",
"Poulsen AA & Ziviani JM (2004). Can I play too? Physical activity engagement of children with DCD. Can J Occup Ther, 71(2).",
"日本作業療法士協会（2020）『学校作業療法実践ガイド』",
]},
{id:26,name:"対人関係困難・友達関係",en:"Social Interaction Difficulties",cat:"学校・社会参加",age:"幼児〜学童",
overview:"アイコンタクト・共同注意・会話の往来・集団遊びへの参加が困難な状態。ASDや発達的な遅れを背景とすることが多い。OTは遊び場面・グループ活動を通じて社会性の発達を支援する。",
observations:[
{name:"遊び場面での社会性の観察",priority:"high",
why:"自由遊び・構造化遊び場面でのアイコンタクト・模倣・共同注意・順番交代・おもちゃの共有・ルール遊びへの参加等を観察し、現在の社会的発達レベルを把握する。",
normal:"発達段階に応じた社会的遊びへの参加（一人→並行→協同遊び）を段階的に支援し、対人インタラクションの機会を意図的に増やす",warn:""},
{name:"ソーシャルスキルトレーニング（SST）のニーズ評価",priority:"high",
why:"あいさつ・依頼・断り方・感情表現・トラブル解決等の具体的なソーシャルスキルの獲得が必要なことが多い。スキルの欠如（知らない）か、パフォーマンスの困難（知っているが使えない）かを評価する。",
normal:"具体的な場面設定でのSST・ロールプレイ・実際の場面での般化練習で社会スキルの習得と般化を支援する",warn:""},
],
refs:[
"Bundy AC et al. (2001). Sensory Integration: Theory and Practice, 2nd ed. FA Davis.",
"Koegel RL & Koegel LK (2006). Pivotal Response Treatments for Autism. Paul H Brookes.",
"日本作業療法士協会（2020）『社会参加支援の手引き―小児編』",
"大隈紘子（監修）（2018）『ソーシャルスキルトレーニングガイドブック』中央法規出版.",
]},
{id:27,name:"実行機能障害（計画・段取り）",en:"Executive Function Difficulties",cat:"学校・社会参加",age:"学童",
overview:"計画立案・優先順位づけ・開始・柔軟な切り替え・モニタリング等の実行機能の弱さ。ADHD・ASD・TBI等で多く見られ、宿題・持ち物管理・集団活動参加に影響する。",
observations:[
{name:"実行機能の評価（BRIEF等）",priority:"high",
why:"BRIEF（行動評定版実行機能評価）等で保護者・教師からの情報を収集し、実行機能の弱い領域（抑制・切り替え・計画等）を特定する。日常場面での具体的な困難との対応を把握する。",
normal:"外部ツール（視覚的スケジュール・チェックリスト・タイマー）で実行機能を補完し、スモールステップで遂行を支援する",warn:""},
{name:"宿題・家庭課題の遂行支援",priority:"high",
why:"宿題の開始困難・途中で気が散る・計画的に進められない・提出を忘れるなどの具体的な困難は実行機能の弱さが主因。保護者とともに家庭での支援体制を構築する。",
normal:"宿題の開始時間の固定化・優先順位リスト・タイマー活用・報酬システム・保護者コーチングで宿題遂行を支援する",warn:""},
],
refs:[
"Gioia GA et al. (2000). BRIEF: Behavior Rating Inventory of Executive Function. Psychological Assessment Resources.",
"Barkley RA (2012). Executive Functions: What They Are, How They Work, and Why They Evolved. Guilford Press.",
"Anderson PJ (2008). Towards a developmental model of executive function. In: Anderson V et al. (eds), Executive Functions and the Frontal Lobes. Taylor & Francis.",
"日本作業療法士協会（2020）『発達障害のある人の作業療法支援』",
]},
{id:28,name:"ワーキングメモリの弱さ",en:"Working Memory Difficulties",cat:"学校・社会参加",age:"学童",
overview:"短期的な情報保持・操作が困難な状態。複数の指示を覚えられない・計算中に数を忘れる・板書を見て写せないなどとして現れる。ADHDや学習障害で多く見られる。",
observations:[
{name:"ワーキングメモリへの影響評価",priority:"high",
why:"複数ステップの口頭指示の実行・暗算・板書の写しなど日常の教育場面での困難を評価する。ワーキングメモリの弱さは「やる気がない」と誤解されやすいため、正確な理解が支援者教育に重要。",
normal:"複数指示の視覚化・一度に一つの指示・メモ帳活用・指示の繰り返し等の外部補完ツールで負荷を軽減する",warn:""},
{name:"補完戦略の指導・定着支援",priority:"mid",
why:"メモを取る・チェックリストを活用するなどの補完戦略を学ぶことで、ワーキングメモリの弱さを補うことができる。戦略の習得には繰り返し練習と日常場面での般化が必要。",
normal:"本人に合った補完ツール（ホワイトボード・メモ帳・スマートフォン等）を選定し、使い方を練習・習慣化まで支援する",warn:""},
],
refs:[
"Gathercole SE & Alloway TP (2008). Working Memory and Learning: A Practical Guide for Teachers. SAGE Publications.",
"Swanson HL (1999). What develops in working memory? Developmental Psychology, 35(4), 986-1000.",
"日本LD学会（編）（2017）『LD・ADHD等関連用語集 第4版』日本文化科学社.",
]},

// ===== 心理・行動 =====
{id:29,name:"癇癪・パニック・感情コントロール",en:"Emotional Dysregulation / Meltdowns",cat:"心理・行動",age:"幼児〜学童",
overview:"感情の調整困難による激しい癇癪・パニック・感情爆発。感覚過敏・感覚処理の困難・実行機能の弱さが背景にあることが多い。OTは感覚的要因の分析と対処戦略の支援を担う。",
observations:[
{name:"癇癪・パニックのトリガー分析",priority:"high",
why:"何がきっかけになっているか（感覚刺激・予定変更・疲労・空腹・特定の人物等）を記録・分析することで、予防的対応が可能になる。ABCチャート（前後関係の記録）が有用。",
normal:"トリガーの特定と環境調整（感覚刺激の軽減・予定の可視化・警告システム）でパニックを予防する",warn:"自傷・他傷を伴うパニックが頻繁→行動支援専門家・医師・心理士との緊急連携"},
{name:"感覚調整の自己コントロール支援",priority:"high",
why:"感覚の過負荷がパニックにつながる場合、自分で感覚調整できるツール（クールダウングッズ・深呼吸・感覚ツール）を習得することで自己制御能力を高められる。",
normal:"クールダウンスペースの設定・感覚ツール（スクィーズ・加重ブランケット等）の活用・感情温度計を使った自己モニタリング支援",warn:""},
{name:"感情の認識・表現スキルの評価",priority:"mid",
why:"感情を言語化・表現できないために行動で表現してしまうことがある。「怒り」「悲しみ」「不安」等の感情の認識と適切な表現方法の習得がパニック軽減につながる。",
normal:"感情カード・感情温度計・気持ちの絵カードを使って感情の認識と表現を練習する",warn:""},
],
refs:[
"Bundy AC et al. (2001). Sensory Integration: Theory and Practice. FA Davis.",
"Greenspan SI & Wieder S (2006). Engaging Autism. Da Capo Lifelong Books.",
"日本作業療法士協会（2020）『発達障害のある人の作業療法支援』",
"奥田健次（2012）『発達障害の子への応用行動分析（ABA）入門』中央法規出版.",
]},
{id:30,name:"不登校・学校不安",en:"School Refusal / School Anxiety",cat:"心理・行動",age:"学童",
overview:"登校しぶり・学校不安・不登校はOTの直接対象ではないが、感覚過敏・協調運動困難・社会性の困難・自己効力感の低下が背景にある場合にOTが貢献できる。",
observations:[
{name:"学校不適応の作業療法的要因の評価",priority:"high",
why:"不登校の背景に感覚過敏（制服・給食・体育等）・書字困難・運動の失敗体験・ADL困難（給食の準備等）・人間関係の困難がある場合、OTが解決できる要因を特定することが重要。",
normal:"OTが対応できる要因（感覚・運動・ADL）を特定し、具体的な対応策（環境調整・合理的配慮等）を学校・心理士・保護者と共有する",warn:"自傷・希死念慮を伴う→医師・心理士への緊急連携"},
{name:"活動参加の段階的回復支援",priority:"mid",
why:"学校への完全復帰だけでなく、放課後の活動・フリースクール・療育での活動参加から始め、徐々に社会参加の幅を広げる段階的アプローチが有効。作業機能の回復を目標とする。",
normal:"本人の興味・強みを活かした活動から始め、成功体験を積み重ねながら参加の場を段階的に広げる",warn:""},
],
refs:[
"文部科学省（2023）『令和4年度児童生徒の問題行動・不登校等生徒指導上の諸課題に関する調査結果』",
"Law M et al. (1998). COPM, 3rd ed. CAOT Publications.",
"日本作業療法士協会（2022）『不登校・ひきこもりのある人への作業療法的アプローチ』",
"奥田健次（2012）『発達障害の子への応用行動分析（ABA）入門』中央法規出版.",
]},

// ===== よくある相談 =====
{id:31,name:"落ち着きがない・多動",en:"Hyperactivity / Restlessness",cat:"よくある相談",age:"幼児〜学童",
overview:"座っていられない・じっとできない・常に動き回るなどの多動性が家庭・保育園・学校で問題になる。ADHD・感覚探求・発達段階の偏りなど複数の要因が関与する。",
observations:[
{name:"多動の感覚的背景の分析",priority:"high",
why:"感覚探求（動き・回転・重い感触を求める）が多動の主要因である場合、感覚ニーズを満たす活動（公園遊び・水遊び・感覚遊び）を計画的に提供することで落ち着きが改善することがある。",
normal:"感覚ダイエットの導入（授業前・帰宅後の感覚活動）・重い物を持つ活動・深圧刺激（タオル体操等）で感覚ニーズを満たす",warn:""},
{name:"環境調整による多動の軽減",priority:"high",
why:"刺激の多い環境（視覚的雑然・騒音等）が覚醒亢進を引き起こし多動が増加することがある。座席の位置・壁の装飾・音環境の調整が有効。",
normal:"刺激の少ない席配置・視覚的刺激の整理・聴覚刺激の軽減・動いてもよい時間の確保で多動を軽減する",warn:"多動が著しく危険行動が频繁→医師への紹介（ADHD診断・薬物療法の検討）"},
],
refs:[
"Dunn W (2014). Sensory Profile 2. Pearson.",
"Barkley RA (2015). Attention-Deficit Hyperactivity Disorder, 4th ed. Guilford Press.",
"日本作業療法士協会（2020）『発達障害のある人の作業療法支援』",
]},
{id:32,name:"不器用さの全般的支援",en:"General Clumsiness",cat:"よくある相談",age:"幼児〜学童",
overview:"「全体的に不器用」という主訴で相談されることが多い。DCD・感覚統合障害・ASDの合併など様々な背景が考えられる。OTは評価で背景を特定し、個別の支援計画を立案する。",
observations:[
{name:"標準化評価による不器用さのプロファイル把握",priority:"high",
why:"MABC-2・VMI・感覚プロファイル等の標準化評価で、不器用さの背景（協調運動・視知覚・感覚処理等）を明らかにする。「なんとなく不器用」から「何がどのくらい困難か」を明確にする。",
normal:"評価結果に基づく個別支援計画の立案・保護者・学校への評価結果のフィードバックで理解と支援を広げる",warn:""},
{name:"本人の意欲・自己効力感の評価",priority:"mid",
why:"不器用さによる失敗体験の蓄積は「どうせできない」という無力感につながる。本人の「やりたい」「困っている」ことを中心に支援することで動機を高め、介入効果を最大化する。",
normal:"COPM等で本人が優先する活動を特定し、本人中心の目標設定で意欲を引き出す",warn:""},
],
refs:[
"Henderson SE, Sugden DA & Barnett AL (2007). MABC-2. Pearson.",
"Law M et al. (1998). COPM, 3rd ed. CAOT Publications.",
"Polatajko HJ & Mandich A (2004). CO-OP Approach. CAOT.",
"辻井正次・宮原資英（監修）（2019）『発達性協調運動障害（DCD）』金子書房.",
]},
{id:33,name:"姿勢が悪い",en:"Poor Posture",cat:"よくある相談",age:"幼児〜学童",
overview:"「姿勢が悪い」「すぐ崩れる」という訴えは体幹筋力・固有受容覚・前庭感覚・視力等が関与することがある。また感覚探求として揺れることもある。OTは原因を評価し環境・活動両面からアプローチする。",
observations:[
{name:"姿勢崩れの要因分析",priority:"high",
why:"「姿勢が悪い」の原因として①体幹筋力不足②固有受容覚・前庭感覚処理③感覚探求（揺れている）④視力の問題⑤環境（椅子のサイズ不適合）等がある。観察と評価で主要因を特定する。",
normal:"原因に応じた対応（体幹強化・感覚統合・椅子高さ調整・視力検査の勧め等）で根本的な改善をはかる",warn:"脊椎の形態異常疑い（側弯・前弯の進行）→医師への報告"},
{name:"学校環境の調整評価",priority:"mid",
why:"学校の椅子と机の高さが体に合っていないだけで姿勢崩れが起きることがある。足底が床につく高さ・肘が机に届く高さが基本。まず環境評価から始めることで早期改善が見込めることがある。",
normal:"椅子の高さ・机の高さの調整・足台の設置・動的シーティングクッションの導入で姿勢環境を整える",warn:""},
],
refs:[
"Rosenblum S & Josman N (2003). Relationship between postural control and fine manual dexterity. Phys Occup Ther Pediatr, 23(4).",
"Ayres AJ (2005). Sensory Integration and the Child. Western Psychological Services.",
"日本作業療法士協会（2020）『姿勢とシーティングの作業療法的アプローチ』",
]},
{id:34,name:"自信がない・自己肯定感が低い",en:"Low Self-Esteem / Low Self-Efficacy",cat:"よくある相談",age:"幼児〜学童",
overview:"発達障害・DCDなどの子どもは失敗体験の蓄積により自己肯定感が低下しやすい。OTはできることを増やし、成功体験を積み重ねることで自己効力感の回復を支援する。",
observations:[
{name:"できることの評価と強みの特定",priority:"high",
why:"OT評価では困難だけでなく「何ができるか」「何が好きか」「どんな強みがあるか」を等しく重視する。強みを活かした活動での成功体験が自己効力感回復の出発点になる。",
normal:"本人の興味・得意なことを活かした課題設定・かならず「できた」体験を積める難易度設定・達成の言語化で自己肯定感を育む",warn:"うつ・希死念慮が見られる→医師・心理士への紹介"},
{name:"活動参加と自己肯定感の循環の支援",priority:"high",
why:"活動参加の成功→自信がつく→新たな挑戦という好循環を作ることがOT支援の目標。本人が「やってみたい」と感じる活動を中心に、参加の質と量を徐々に広げる。",
normal:"COPM等で本人の目標を中心に置いた支援・定期的な達成の評価と共有・小さな進歩の可視化で動機を維持する",warn:""},
],
refs:[
"Law M et al. (1998). COPM, 3rd ed. CAOT Publications.",
"Bandura A (1997). Self-Efficacy: The Exercise of Control. Freeman.",
"Missiuna C et al. (2006). A 'clumsy child'. Can J Occup Ther, 73(2).",
"日本作業療法士協会（2020）『作業療法における目標設定と評価ガイド』",
]},
{id:35,name:"偏食",en:"Food Selectivity / Picky Eating",cat:"よくある相談",age:"幼児〜学童",
overview:"特定の食感・色・温度・匂いへの強い拒否反応により食べられる食品が著しく制限される状態。口腔感覚過敏・感覚統合障害・ASDに多く見られる。OTはSTと連携して感覚的要因にアプローチする。",
observations:[
{name:"食べられる食品と拒否パターンの分析",priority:"high",
why:"拒否の多い食感（ぐにゃっとした・ざらざらした・混ざった等）・色・温度・匂いのパターンを詳細に把握する。「嫌いなもの」と「食べられないもの（感覚的に処理できない）」は区別して支援する。",
normal:"食べられる食材を分析し、共通する食感・形状から近い食品に段階的に拡げる。一口チャレンジなど楽しめるアプローチを取る",warn:"著しい偏食で体重増加不良・栄養不足→ST・医師・栄養士への紹介"},
{name:"口腔感覚脱感作アプローチ",priority:"high",
why:"口腔内の触覚過敏（口の中に物が入ることへの強い抵抗）が偏食の根本原因の場合、脱感作アプローチが有効。顔・口周り・口腔内への段階的な触覚刺激慣らしが前提となる。",
normal:"顔・口周りへの触覚慣らし→歯ブラシによる口腔内刺激→食感の段階的拡大というプログラムでアプローチする",warn:""},
],
refs:[
"Dunn W (2014). Sensory Profile 2. Pearson.",
"Morris SE & Klein MD (2000). Pre-Feeding Skills, 2nd ed. Therapy Skill Builders.",
"Cermak SA et al. (2010). Food selectivity and sensory sensitivity in children with autism spectrum disorders. J Am Diet Assoc, 110(2), 238-246.",
"日本摂食嚥下リハビリテーション学会（2018）『嚥下障害のある子どもへの支援ガイドライン』",
]},
{id:36,name:"学校に行きたがらない（OT視点）",en:"School Refusal (OT Perspective)",cat:"よくある相談",age:"学童",
overview:"学校不安・登校しぶりの背景にOTが関与できる要因（感覚・運動・ADL困難）が隠れていることがある。「なぜ学校が嫌か」の作業療法的アセスメントが支援の出発点となる。",
observations:[
{name:"学校生活のどの場面で困難があるかの評価",priority:"high",
why:"給食（偏食・食器操作）・体育（運動困難）・図工（手先の不器用さ）・着替え（更衣困難）・感覚刺激（音・光・制服）など具体的な困難場面をリストアップし、OTが貢献できる領域を特定する。",
normal:"特定した困難場面に対する具体的対応策（合理的配慮・環境調整・補助具・練習）を担任・学校との連携で実施する",warn:"不登校が長期化・心理的健康の悪化→心理士・医師との緊急連携"},
{name:"本人の「やりたい」「得意」の確認",priority:"mid",
why:"学校不安がある子どもでも、放課後活動・療育・習い事など別の場での成功体験が自信回復のきっかけになることがある。OTは本人の強みと興味を活かせる場を見つけることも支援の一部。",
normal:"学校以外の活動参加（療育・習い事・地域活動）での成功体験を積み重ね、社会参加の基盤を維持・拡大する",warn:""},
],
refs:[
"文部科学省（2023）『令和4年度児童生徒の問題行動・不登校等生徒指導上の諸課題に関する調査結果』",
"Law M et al. (1998). COPM, 3rd ed. CAOT Publications.",
"日本作業療法士協会（2022）『不登校・ひきこもりのある人への作業療法的アプローチ』",
]},
];

const otCategories = [
  "すべて",
  "発達障害",
  "神経・先天性疾患",
  "感覚統合",
  "運動・協調",
  "日常生活（ADL）",
  "学校・社会参加",
  "心理・行動",
  "よくある相談",
];

const otCatColors = {
  "発達障害":"#2f9e44",
  "神経・先天性疾患":"#862e9c",
  "感覚統合":"#d9480f",
  "運動・協調":"#1971c2",
  "日常生活（ADL）":"#f08c00",
  "学校・社会参加":"#0c8599",
  "心理・行動":"#c92a2a",
  "よくある相談":"#5c7cfa",
};
